apiVersion: v1
kind: Secret
metadata:
  name: dagster-space-track
  namespace: dagster
type: Opaque
stringData:
  SPACE_TRACK_IDENTITY: "pradovalmur@outlook.com"
  SPACE_TRACK_PASSWORD: "N7Xa_Q.3Spct3S5"