apiVersion: v1
kind: Namespace
metadata:
  name: orchestration

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: orchestration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  namespace: orchestration
  labels:
    app: airflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_DB
              value: airflow
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
          ports:
            - containerPort: 5432
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: orchestration
spec:
  selector:
    app: airflow-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-env
  namespace: orchestration
type: Opaque
stringData:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow

  AIRFLOW__CORE__EXECUTOR: LocalExecutor
  AIRFLOW__CORE__FERNET_KEY: zkkfylToKRbUTQ8PjoMO6z1qvSbCvZUBMFFWWnf36X8
  AIRFLOW__CORE__LOAD_EXAMPLES: "False"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: Europe/Lisbon

  AIRFLOW__CORE__DAGS_FOLDER: /opt/airflow/dags/repo

  AIRFLOW__WEBSERVER__RBAC: "True"
  AIRFLOW__WEBSERVER__AUTHENTICATE: "True"
  AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "True"

---
apiVersion: v1
kind: Secret
metadata:
  name: airflow-admin
  namespace: orchestration
type: Opaque
stringData:
  AIRFLOW_ADMIN_USERNAME: admin
  AIRFLOW_ADMIN_PASSWORD: super-secret-admin
  AIRFLOW_ADMIN_EMAIL: admin@example.com

---
apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-create-admin
  namespace: orchestration
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: create-admin
          image: apache/airflow:2.10.2
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for Postgres..."
              until nc -z postgres 5432; do
                echo "Postgres not ready, sleeping..."
                sleep 3
              done

              echo "Running db migrate..."
              airflow db migrate

              echo "Creating admin user..."
              airflow users create \
                --role Admin \
                --username "$AIRFLOW_ADMIN_USERNAME" \
                --firstname Admin \
                --lastname User \
                --email "$AIRFLOW_ADMIN_EMAIL" \
                --password "$AIRFLOW_ADMIN_PASSWORD" || true

              echo "Done."
          envFrom:
            - secretRef:
                name: airflow-env
            - secretRef:
                name: airflow-admin

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: orchestration
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.10.2
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for Postgres..."
              until nc -z postgres 5432; do
                echo "Postgres not ready, sleeping..."
                sleep 3
              done

              echo "Running db migrate..."
              airflow db migrate

              echo "Starting scheduler..."
              exec airflow scheduler
          envFrom:
            - secretRef:
                name: airflow-env
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs

        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/pradovalmur/k8s-dataplataform-dags.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_WAIT
              value: "30"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /git

      volumes:
        - name: dags
          emptyDir: {}
        - name: logs
          emptyDir: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: orchestration
  labels:
    app: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: webserver
          image: apache/airflow:2.10.2
          imagePullPolicy: IfNotPresent
          command: ["bash", "-c"]
          args:
            - |
              echo "Waiting for Postgres..."
              until nc -z postgres 5432; do
                echo "Postgres not ready, sleeping..."
                sleep 3
              done

              echo "Starting webserver..."
              exec airflow webserver --port 8080
          envFrom:
            - secretRef:
                name: airflow-env
          ports:
            - containerPort: 8080
              name: web
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
          readinessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 40
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 80
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30

        - name: git-sync
          image: registry.k8s.io/git-sync/git-sync:v4.2.3
          imagePullPolicy: IfNotPresent
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/pradovalmur/k8s-dataplataform-dags.git"
            - name: GIT_SYNC_BRANCH
              value: "main"
            - name: GIT_SYNC_ROOT
              value: "/git"
            - name: GIT_SYNC_DEST
              value: "repo"
            - name: GIT_SYNC_WAIT
              value: "30"
            - name: GIT_SYNC_ONE_TIME
              value: "false"
          volumeMounts:
            - name: dags
              mountPath: /git

      volumes:
        - name: dags
          emptyDir: {}
        - name: logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: orchestration
  labels:
    app: airflow-webserver
spec:
  type: ClusterIP
  selector:
    app: airflow-webserver
  ports:
    - name: http
      port: 8080
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airflow-ingress
  namespace: orchestration
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: airflow.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: airflow-web
                port:
                  number: 8080