apiVersion: v1
kind: Namespace
metadata:
  name: cattle-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rancher
  namespace: cattle-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-cluster-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: rancher
    namespace: cattle-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: cattle-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      serviceAccountName: rancher
      containers:
        - name: rancher
          image: rancher/rancher:v2.9.2
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443
          env:
            - name: CATTLE_SERVER_URL
              value: "https://rancher.chameleonmountain.com"
            - name: CATTLE_TLS
              value: "external"
            - name: CATTLE_BOOTSTRAP_PASSWORD
              value: "admin123"
---
apiVersion: v1
kind: Service
metadata:
  name: rancher
  namespace: cattle-system
spec:
  type: ClusterIP
  selector:
    app: rancher
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
