kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: k8-dataplataform

nodes:
  - role: control-plane
    image: kindest/node:v1.29.0
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP

  - role: worker
    image: kindest/node:v1.29.0

  - role: worker
    image: kindest/node:v1.29.0

  