FROM apache/airflow:2.10.2

USER root
RUN apt-get update && apt-get install -y --no-install-recommends git && rm -rf /var/lib/apt/lists/*
USER airflow

# instala com constraints do Airflow 2.10.2 (python 3.12)
RUN pip install --no-cache-dir \
  --constraint https://raw.githubusercontent.com/apache/airflow/constraints-2.10.2/constraints-3.12.txt \
  "astronomer-cosmos" \
  "dbt-core" \
  "dbt-trino"
